INSERT INTO WN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (1, 'TRAIN-LAW', '법령', 'TRAIN', 0);
INSERT INTO WN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (2, 'TRAIN-GUIDE', '지침', 'TRAIN', 1);
INSERT INTO WN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (3, 'TRAIN-MANUAL', '메뉴얼', 'TRAIN', 2);
INSERT INTO WN_COMN_CODE(CODE_ID, CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES (4, 'TRAIN-EDU', '교육 자료', 'TRAIN', 3);