server:
  port: 8080
spring:
  application:
    name: extractor
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
engine:
  collection:
    connect-timeout: 5000
    response-timeout: 300000
    read-timeout: 300000
    write-timeout: 300000
    host: localhost
    port: 9200
  indexer:
    connect-timeout: 5000
    response-timeout: 300000
    read-timeout: 300000
    write-timeout: 300000
    host: localhost
    port: 9200
  embed:
    connect-timeout: 5000
    response-timeout: 300000
    read-timeout: 300000
    write-timeout: 300000
    host: localhost
    port: 8000
    path: /embed
  search:
    connect-timeout: 5000
    response-timeout: 300000
    read-timeout: 300000
    write-timeout: 300000
    host: localhost
    port: 9200
  reranker:
    connect-timeout: 5000
    response-timeout: 300000
    read-timeout: 300000
    write-timeout: 300000
    host: localhost
    port: 8001
    path: /rerank
env:
  jwt:
    secret: REDACTED_JWT_SECRET
    access-token-expiry: 3600000
    refresh-token-expiry: 604800000
    refresh-token-cookie-name: refreshToken
  file:
    file-store-path: /Users/tableminpark/IdeaProjects/rag-extractor/fileStoreLocal
    temp-dir: temp
