INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-LAW', '법령', 'TRAIN', 0);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-GUIDE', '지침', 'TRAIN', 1);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-MANUAL', '메뉴얼', 'TRAIN', 2);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-EDU', '교육 자료', 'TRAIN', 3);

INSERT INTO GEN_MEMBER(MEMBER_ID, NAME, PASSWORD, ROLE) VALUES (-1, 'admin', '$2a$10$cH7t5bKohqOLsinLWOenaulHR/7jdlismKhGDSFPZdJUgw3jzuzVO', 'ADMIN');
INSERT INTO GEN_MEMBER(MEMBER_ID, NAME, PASSWORD, ROLE) VALUES (-2, 'manager', '$2a$10$0/nMpN32/Nr1TWtLPD1gq.yCYVd29p55SH0O/Dxedfzzb5K6vXX4G', 'MANAGER');
INSERT INTO GEN_MEMBER(MEMBER_ID, NAME, PASSWORD, ROLE) VALUES (-3, 'trainer', '$2a$10$qM0Wgg7MOZHzheIH13nwYuvCiaXxKjfkVANp2Qkcet/5ndFVCzAry', 'NORMAL');