INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-LAW', '법령', 'TRAIN', 0);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-GUIDE', '지침', 'TRAIN', 1);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-MANUAL', '메뉴얼', 'TRAIN', 2);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-EDU', '교육 자료', 'TRAIN', 3);

INSERT INTO GEN_MEMBER(USER_ID, EMAIL, NAME, PASSWORD, ROLE) VALUES ('admin', 'admin@example.com', 'admin', '$2a$10$9Wt.OFBQH95Kfn1DIr2T..RIyHt5x4C7v6dEWXTh14BR.iiMeRwSS', 'ROLE_ADMIN');
INSERT INTO GEN_MEMBER(USER_ID, EMAIL, NAME, PASSWORD, ROLE) VALUES ('manager', 'manager@example.com', 'manager', '$2a$10$/tkv165OxsdLFF6XeLEWaeOpuizws6bz3.ouxuUpTz.ZZ/pW6AUPi', 'ROLE_MANAGER');
INSERT INTO GEN_MEMBER(USER_ID, EMAIL, NAME, PASSWORD, ROLE) VALUES ('trainer', 'trainer@example.com', 'trainer', '$2a$10$eMca4BbpEkyogpZESuBLJ.xX3OmIHOD4aKPtUSnXocwoE1Cwt92uq', 'ROLE_USER');
