INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-LAW', '법령', 'TRAIN', 0);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-GUIDE', '지침', 'TRAIN', 1);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-MANUAL', '메뉴얼', 'TRAIN', 2);
INSERT INTO GEN_COMMON_CODE(CODE, CODE_NAME, CODE_GROUP, SORT_ORDER) VALUES ('TRAIN-EDU', '교육 자료', 'TRAIN', 3);

INSERT INTO GEN_MEMBER(EMAIL, NAME, PASSWORD, ROLE) VALUES ('admin', 'admin', '$2b$10$PhIAUO.HiQANc9ykN1QFKeYxZYTt.es/z1SlX4DNSka6QSCoVbPSK', 'ADMIN');
INSERT INTO GEN_MEMBER(EMAIL, NAME, PASSWORD, ROLE) VALUES ('manager', 'manager', '$2b$10$6xae7SrTxmPXqkdACndPqOwVrcQkT0/rCBUXqFPlPrEULcwrzNLDe', 'MANAGER');
INSERT INTO GEN_MEMBER(EMAIL, NAME, PASSWORD, ROLE) VALUES ('trainer', 'trainer', '$2b$10$RYP9FFt5ced58yC3a5VUAuiJW0iK0m3wa6URMLuVCGI0FcMpoGthe', 'NORMAL');